my_project/config/routes.rb
Rails.application.routes.draw do
  resources :tweets, :zombies
  root to: "tweets#index"
  get ':name' => 'tweets#index', as: 'zombie_tweets'
  get '/all' => redirect('/tweets')
  get '/local_tweets/:zipcode' => 'tweets#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

my_project/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

my_project/app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :zombie
end

my_project/app/models/zombie.rb
class Zombie < ApplicationRecord
 has_many :tweets
end

my_project/app/controllers/tweets_controller.rb
class TweetsController <  ApplicationController
 before_action :get_tweet, only: [ :edit, :update, :destroy ]
 before_action :check_auth, only: [ :edit, :update, :destroy ]
 def index
  if params[:name]
   @zombie = Zombie.where(name: params[:name]).first
   @tweets = @zombie.tweets
  else 
   @tweets = Tweet.all
  end
  respond_to do |format|
   format.html # index.html.erb
   format.xml { render xml: @tweets }
   format.json { render json: @tweets }
  end
 end
 def get_tweet
  @tweet = Tweet.find(params[:id])
 end

 def check_auth
  if session[:zombie_id] != @tweet.zombie_id
     flash[:notice] = "Sorry, you can't edit this tweet"
     redirect_to tweets_path
  end
 end
 def destroy

 end
 def edit
  @tweet = Tweet.find(params[:id])
  if session[:zonbie_id] != @tweet.zombie_id
   flash[:notice] = "Sorry, you can't edit this tweet"
   redirect_to(tweets_path)
  end
 end
  #render action: 'status' untuk ngelempar jika orang buka show dilempar ke status.html.erb
end

my_project/app/controllers/zombies_controller.rb
class ZombiesController <  ApplicationController

end

my_project/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyProject</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:notice] %>
     <div id="notice"> <%= flash[:notice] %></div>
    <% end %>
    <%= yield %>
  </body>
</html>

my_project/app/views/tweets/index.html.erb
<h1>Listing Tweets</h1>
<table>
 <tr>
  <th>Id</th>
  <th>Status</th>
  <th>Zombie</th>
 </tr>
<% tweets = Tweet.all %>
<% tweets.all.each do |tweet| %>
 <tr>
  <td> <%= tweet.id %> </td>
  <td> <%= tweet.status %></td>
  <td> <%= link_to tweet.zombie.name, tweet.zombie %> </td>
  <td> <%= link_to "Edit", edit_tweet_path(tweet) %></td>
  <td> <%= link_to "Destroy", tweet, method: :delete %></td>

 </tr>
<% end %>
</table>

<% if tweets.size == 0 %>
 <em>No Tweets Found</em>
<% end %>

my_project/app/views/tweets/show.html.erb
 <h1><%= @tweet.status %></h1>
 <p> Posted by 

  <%= link_to @tweet.zombie.name, 
   tweets_path(@tweet.zombie), 
   data: {confirm: 'Are you sure?'}
  %> 
 </p>